import type { ReportDocument } from "./types";

const KHMER_PARAGRAPH =
	"មនុស្សទាំងអស់កើតមកមានសេរីភាព និងសមភាពគ្នា ក្នុងផ្នែកសេចក្តីថ្លៃថ្នូរ និងសិទ្ធិ។ " +
	"មនុស្សគ្រប់រូបមានវិចារណញាណនិងសតិសម្បជញ្ញៈ ហើយត្រូវប្រព្រឹត្ដចំពោះគ្នាទៅវិញទៅមក " +
	"ក្នុងន័យសុភាពភាតរភាព។";

export const sampleReportDocument: ReportDocument = {
	version: 1,
	pages: ["page-1"],
	assets: {},
	fonts: {},
	nodes: {
		"page-1": {
			id: "page-1",
			type: "page",
			parentId: null,
			children: ["title-text", "khmer-text", "divider-line", "border-rect"],
			name: "Page 1",
			visible: true,
			locked: false,
			opacity: 1,
			frame: { x: 0, y: 0, width: 595.28, height: 841.89, rotation: 0 },
			paper: { preset: "A4", orientation: "portrait" },
			margin: { top: 48, right: 48, bottom: 48, left: 48 },
			background: "#ffffff",
		},
		"title-text": {
			id: "title-text",
			type: "text",
			parentId: "page-1",
			children: [],
			name: "Title",
			visible: true,
			locked: false,
			opacity: 1,
			frame: { x: 48, y: 48, width: 499.28, height: 40, rotation: 0 },
			text: "Sample Report",
			style: {
				fontFamily: "Inter",
				fontSize: 24,
				fontWeight: 700,
				fontStyle: "normal",
				color: "#111111",
				lineHeight: 1.2,
				letterSpacing: 0,
				align: "left",
				verticalAlign: "top",
				decoration: "none",
				wrap: true,
			},
		},
		"khmer-text": {
			id: "khmer-text",
			type: "text",
			parentId: "page-1",
			children: [],
			name: "Khmer paragraph",
			visible: true,
			locked: false,
			opacity: 1,
			frame: { x: 48, y: 110, width: 240, height: 220, rotation: 0 },
			text: KHMER_PARAGRAPH,
			style: {
				fontFamily: "Noto Sans Khmer",
				fontSize: 14,
				fontWeight: 400,
				fontStyle: "normal",
				color: "#222222",
				lineHeight: 1.6,
				letterSpacing: 0,
				align: "left",
				verticalAlign: "top",
				decoration: "none",
				wrap: true,
			},
		},
		"divider-line": {
			id: "divider-line",
			type: "line",
			parentId: "page-1",
			children: [],
			name: "Divider",
			visible: true,
			locked: false,
			opacity: 1,
			frame: { x: 48, y: 350, width: 499.28, height: 0, rotation: 0 },
			x1: 0,
			y1: 0,
			x2: 499.28,
			y2: 0,
			stroke: { color: "#cccccc", width: 1 },
		},
		"border-rect": {
			id: "border-rect",
			type: "rect",
			parentId: "page-1",
			children: [],
			name: "Border box",
			visible: true,
			locked: false,
			opacity: 1,
			frame: { x: 320, y: 110, width: 227.28, height: 100, rotation: 0 },
			fill: { color: "#f5f5f5" },
			stroke: { color: "#999999", width: 1 },
			radius: 4,
		},
	},
};

/**
 * Fixture for cross-adapter parity tests: exercises the spots most likely to
 * drift between CanvasAdapter and SkiaAdapter — Khmer text wrapping,
 * underline decoration (drawn manually on one backend vs. natively on the
 * other), and a rotated node.
 */
export const parityFixtureDocument: ReportDocument = {
	version: 1,
	pages: ["page-1"],
	assets: {},
	fonts: {},
	nodes: {
		"page-1": {
			id: "page-1",
			type: "page",
			parentId: null,
			children: ["khmer-text", "underline-text", "rotated-rect"],
			name: "Page 1",
			visible: true,
			locked: false,
			opacity: 1,
			frame: { x: 0, y: 0, width: 400, height: 400, rotation: 0 },
			paper: {
				preset: "Custom",
				orientation: "portrait",
				width: 400,
				height: 400,
			},
			margin: { top: 0, right: 0, bottom: 0, left: 0 },
			background: "#ffffff",
		},
		"khmer-text": {
			id: "khmer-text",
			type: "text",
			parentId: "page-1",
			children: [],
			name: "Khmer paragraph",
			visible: true,
			locked: false,
			opacity: 1,
			frame: { x: 16, y: 16, width: 200, height: 180, rotation: 0 },
			text: KHMER_PARAGRAPH,
			style: {
				fontFamily: "Noto Sans Khmer",
				fontSize: 14,
				fontWeight: 400,
				fontStyle: "normal",
				color: "#222222",
				lineHeight: 1.6,
				letterSpacing: 0,
				align: "left",
				verticalAlign: "top",
				decoration: "none",
				wrap: true,
			},
		},
		"underline-text": {
			id: "underline-text",
			type: "text",
			parentId: "page-1",
			children: [],
			name: "Underlined text",
			visible: true,
			locked: false,
			opacity: 1,
			frame: { x: 16, y: 220, width: 200, height: 30, rotation: 0 },
			text: "Underlined text",
			style: {
				fontFamily: "Inter",
				fontSize: 16,
				fontWeight: 400,
				fontStyle: "normal",
				color: "#111111",
				lineHeight: 1.2,
				letterSpacing: 0,
				align: "left",
				verticalAlign: "top",
				decoration: "underline",
				wrap: true,
			},
		},
		"rotated-rect": {
			id: "rotated-rect",
			type: "rect",
			parentId: "page-1",
			children: [],
			name: "Rotated rect",
			visible: true,
			locked: false,
			opacity: 1,
			frame: { x: 260, y: 260, width: 80, height: 50, rotation: 15 },
			fill: { color: "#cce5ff" },
			stroke: { color: "#3366cc", width: 2 },
		},
	},
};
